apiVersion: v2
appVersion: v4.0.2
dependencies:
- condition: elasticsearch.enabled
  name: elasticsearch
  repository: file://./charts/elasticsearch
- condition: postgresql.enabled
  name: postgresql
  repository: file://./charts/postgresql
- name: redis
  repository: file://./charts/redis
description: Mastodon is a free, open-source social network server based on ActivityPub.
name: mastodon
type: application
version: 3.0.1+up3.0.0
