apiVersion: v1
entries:
  traefik:
  - apiVersion: v1
    appVersion: 2.1.1
    created: "2020-01-20T12:53:15.948569411-08:00"
    description: A Traefik based Kubernetes ingress controller
    digest: ba5892af3a77d1e3dfa8ad3bc3c8623149ecc89ffbb458aabc6f5711f053e492
    home: https://traefik.io/
    icon: http://traefik.io/traefik.logo.png
    keywords:
    - traefik
    - ingress
    maintainers:
    - email: emile@vauge.com
      name: emilevauge
    - email: daniel.tomcej@gmail.com
      name: dtomcej
    - email: ludovic@containo.us
      name: ldez
    name: traefik
    sources:
    - https://github.com/containous/traefik
    urls:
    - https://brandond.github.io/helm/charts/traefik-3.1.0.tgz
    version: 3.1.0
generated: "2020-01-20T12:53:15.947024291-08:00"
