apiVersion: v1
entries:
  traefik:
  - apiVersion: v2
    appVersion: 2.4.8
    created: "2021-07-03T03:00:46.199166003-07:00"
    description: A Traefik based Kubernetes ingress controller
    digest: 545ad9118e77804ed7189315e7466e4c5d82a86af82ff41319fc46eb24b6f236
    home: https://traefik.io/
    icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
    keywords:
    - traefik
    - ingress
    maintainers:
    - email: emile@vauge.com
      name: emilevauge
    - email: daniel.tomcej@gmail.com
      name: dtomcej
    - email: ldez@traefik.io
      name: ldez
    name: traefik
    sources:
    - https://github.com/traefik/traefik
    - https://github.com/traefik/traefik-helm-chart
    type: application
    urls:
    - https://brandond.github.io/helm/charts/traefik-9.20.0.tgz
    version: 9.20.0
generated: "2021-07-03T03:00:46.196370011-07:00"
